[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Douglas Anderson <hockeybuggy@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
assert_approx_eq = "1.1.0"
criterion = "0.3"

[[bench]]
name = "simple_world"
harness = false
